sudo: required

language: node_js

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

install:
  - npm ci

script:
  - npm run test

matrix:
  include:
  - name: "Linux (Legacy Node)"
    os: linux
    dist: bionic
    # See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
    services:
      - xvfb
    node_js:
      - 8
  - name: "Linux (Latest Node)"
    os: linux
    dist: bionic
    # See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
    services:
      - xvfb
    node_js:
      - 12
  - name: "OS X (Latest Node)"
    os: osx
    node_js:
      - 12
    before_script:
      # See https://github.com/GoogleChromeLabs/selenium-assistant/issues/118
      - "sudo /usr/bin/safaridriver --enable"
      - "sudo defaults write com.apple.Safari AllowRemoteAutomation 1"
